---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Ds Viewer service on {{ inventory_hostname }}
      template:
        src: systemd/ds_viewer.service.j2
        dest: /etc/systemd/system/ds_viewer.service
      register: ds_viewer_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Ds Viewer service on {{ inventory_hostname }}
      systemd:
        name: ds_viewer.service
        enabled: yes
      when: ds_viewer_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]