---
- name: Setup Filebeat on {{ inventory_hostname }}
  block:
    # Download Filebeat distribution and unzip in /opt as zip has folder filebeat-x.x.x
    - name: Download and unarchive Filebeat on {{ inventory_hostname }}
      unarchive:
        src: "{{ filebeat.distribution_url }}"
        remote_src: yes
        dest: "{{ server.apps_dir }}"
        creates: "{{ filebeat.dir }}"
        owner: "{{ server.user }}"
        group: "{{ server.group }}"
      register: filebeat_download

    - name: Fix permissions to filebeat dir on {{ inventory_hostname }}
      shell:
        cmd: chown -R "{{ server.user }}":"{{ server.group }}" "{{ filebeat.dir }}"-*
        warn: false
      when: filebeat_download.changed

    - name: Create simbolic link between filebeat-x.x.x and filebeat directory on {{ inventory_hostname }}
      shell:
        cmd: find . -maxdepth 1 -type d -iname 'filebeat-*' -exec ln -s {} "{{ filebeat.dir }}" \;
        chdir: "{{ server.apps_dir }}"
        creates: "{{ filebeat.dir }}"
      when: filebeat_download.changed

    - name: Config Filebeat filebeat.yml on {{ inventory_hostname }}
      template:
        src: "filebeat/filebeat.yml.j2"
        dest: "{{ filebeat.dir + '/filebeat.yml'}}"
      when: filebeat_download.changed

#    - name: Start Filebeat on {{ inventory_hostname }}
#      shell:
#        cmd: nohup ./filebeat run -e >> filebeat.log 2>&1 &
#        chdir: "{{ filebeat.dir }}"
#      become_user: "{{ server.user }}"
#      when: filebeat_download.changed

    - name: Config Filebeat service on {{ inventory_hostname }}
      template:
        src: systemd/filebeat.service.j2
        dest: /etc/systemd/system/filebeat.service
      when: filebeat_download.changed
      register: filebeat_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes
      when: filebeat_service.changed

    - name: Enable/Start Filebeat service on {{ inventory_hostname }}
      systemd:
        name: filebeat.service
        enabled: yes
        state: started
      when: filebeat_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Setup Filebeat"
  always:
    - debug:
        msg: "Setup Filebeat FINISHED"
  tags: ["install_software"]