---
- name: Configure startup programs on {{ inventory_hostname }}
  block:
    - name: Config Filebeat service on {{ inventory_hostname }}
      template:
        src: systemd/filebeat.service.j2
        dest: /etc/systemd/system/filebeat.service
      register: filebeat_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Filebeat service on {{ inventory_hostname }}
      systemd:
        name: filebeat.service
        enabled: yes
      when: filebeat_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]