- name: Setting up server with Node exporter on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: update_app_checker.yml
      vars:
        app_dir: "{{ node_exporter.dir }}"
        app_version: "{{ node_exporter_version }}"
        output_fact: node_exporter_will_update

    - import_tasks: u1-prepare_for_update.yml
      when: node_exporter_will_update
      tags: [prepare_for_update]

    - import_tasks: 03-setup_node_exporter.yml
      tags: [setup_node_exporter]

    - include_role:
        name: nginx
      vars:
        sites:
          node_exporter:
            ssl_enabled: true
            external_port: "{{ node_exporter.http_port }}"
            internal_port: "{{ node_exporter.http_internal_port }}"
            internal_protocol: "http"
            domain: "_"

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Node exporter on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Node exporter FINISHED on {{ inventory_hostname }}"
  tags: ["node_exporter"]
