---
- name: Preparing required packages
  block:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required package dependencies
      apt:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - openjdk-8-jre
          - unzip
          - apt-transport-https
          - libcurl4
          - openssl
          - python-apt

    - name: Copy check_port script
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: no
        owner: "{{ server.user }}"
        group: "{{ server.group }}"
        mode: a+x
      with_items:
        - { src: 'misc/check_port.sh', dest: '{{ server.apps_dir}}' }
      register: check_port

    - name: Create permanent environment variables on /etc/environment (which is system-wide, all users)
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: "^{{ item.key | regex_escape() }}="
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ os_environment_variables }}"

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Prepare required packages"
  always:
    - debug:
        msg: "Prepare required packages FINISHED"