---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Grafana service on {{ inventory_hostname }}
      template:
        src: systemd/grafana.service.j2
        dest: /etc/systemd/system/grafana.service
      register: grafana_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Grafana service on {{ inventory_hostname }}
      systemd:
        name: grafana.service
        enabled: yes
      when: grafana_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]