- name: Setting up server with Grafana on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: update_app_checker.yml
      vars:
        app_dir: "{{ grafana.dir }}"
        app_version: "{{ grafana_version }}"
        output_fact: grafana_will_update

    - import_tasks: u1-prepare_for_update.yml
      when: grafana_will_update
      tags: [prepare_for_update]

    - import_tasks: 03-setup_grafana.yml
      tags: [setup_grafana]

    - include_role:
        name: nginx
      vars:
        sites:
          grafana:
            ssl_enabled: false
            external_port: "{{ grafana.http_port }}"
            internal_port: "{{ grafana.http_internal_port }}"
            internal_protocol: "https"
            domain: "{{ grafana.domain }}"
          grafana_secure:
            ssl_enabled: true
            external_port: "{{ grafana.https_port }}"
            internal_port: "{{ grafana.http_internal_port }}"
            internal_protocol: "https"
            domain: "{{ grafana.domain }}"

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Grafana on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Grafana FINISHED on {{ inventory_hostname }}"
  tags: ["grafana"]
