---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Elasticsearch service on {{ inventory_hostname }}
      template:
        src: systemd/elasticsearch.service.j2
        dest: /etc/systemd/system/elasticsearch.service
      register: elasticsearch_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Elasticsearch service on {{ inventory_hostname }}
      systemd:
        name: elasticsearch.service
        enabled: yes
      when: elasticsearch_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]