---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Mongodb service on {{ inventory_hostname }}
      template:
        src: systemd/mongodb.service.j2
        dest: /etc/systemd/system/mongodb.service
      register: mongodb_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Mongodb service on {{ inventory_hostname }}
      systemd:
        name: mongodb.service
        enabled: yes
      when: mongodb_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]