- name: Setting up server with Mongodb on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    # mongodb_will_update was initially generated as a fact in site.yml
    - import_tasks: u1-prepare_for_update.yml
      when: mongodb_will_update
      tags: [prepare_for_update]

    - import_tasks: 03-setup_mongodb.yml
      tags: [setup_mongodb]

    - import_tasks: update_app_checker.yml
      vars:
        app_dir: "{{ mongodb.database_tools.dir }}"
        app_version: "{{ mongodb_database_tools_version }}"
        output_fact: mongodb_database_tools_will_update

    - import_tasks: u2-prepare_db_tools_for_update.yml
      when: mongodb_database_tools_will_update
      tags: [prepare_for_update]

    - import_tasks: 04-setup_mongodb_database_tools.yml
      tags: [setup_mongodb]

    - import_tasks: 05-backup_mongodb.yml
      tags: [backup_mongodb]

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Mongodb on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Mongodb FINISHED on {{ inventory_hostname }}"
  tags: ["mongodb"]
