---
- name: Preparing required packages on {{ inventory_hostname }}
  block:
    - name: Install required package dependencies on {{ inventory_hostname }}
      apt:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - openjdk-8-jre
          - unzip
          - apt-transport-https
          - libcurl4
          - openssl
          - python-apt
          - python-pip
          - python3-pip
          - python-setuptools

    - name: Create permanent environment variables on /etc/environment (which is system-wide, all users) on {{ inventory_hostname }}
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: "^{{ item.key | regex_escape() }}="
        line: "{{ item.key }}={{ item.value}}"
      with_items: "{{ os_environment_variables }}"

    - name: Install Python package boto3 with pip required by aws_s3 module on {{ inventory_hostname }}
      pip:
        name: boto3

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Prepare required packages on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Prepare required packages FINISHED on {{ inventory_hostname }}"
  tags: ["prepare_packages"]
