---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Cordra service on {{ inventory_hostname }}
      template:
        src: systemd/cordra.service.j2
        dest: /etc/systemd/system/cordra.service
      register: cordra_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Cordra service on {{ inventory_hostname }}
      systemd:
        name: cordra.service
        enabled: yes
      when: cordra_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]