---
- name: Configure startup programs on {{ inventory_hostname }}
  block:
    - name: Config Blackbox Exporter service on {{ inventory_hostname }}
      template:
        src: systemd/blackbox_exporter.service.j2
        dest: /etc/systemd/system/blackbox_exporter.service
      register: blackbox_exporter_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Blackbox Exporter service on {{ inventory_hostname }}
      systemd:
        name: blackbox_exporter.service
        enabled: yes
      when: blackbox_exporter_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]