- name: Setting up server with Prometheus on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: update_app_checker.yml
      vars:
        app_dir: "{{ prometheus.dir }}"
        app_version: "{{ prometheus_version }}"
        output_fact: prometheus_will_update

    - import_tasks: u1-prepare_for_update.yml
      when: prometheus_will_update
      tags: [prepare_for_update]

    - import_tasks: 03-setup_prometheus.yml
      tags: [setup_prometheus]

    - include_role:
        name: nginx
      vars:
        sites:
          prometheus:
            ssl_enabled: true
            external_port: "{{ prometheus.http_port }}"
            internal_port: "{{ prometheus.http_internal_port }}"
            internal_protocol: "http"
            domain: "_"

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Prometheus on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Prometheus FINISHED on {{ inventory_hostname }}"
  tags: ["prometheus"]
