---
- name: Configure network on {{ inventory_hostname }}
  # Comment: Currently no ports are opened because the rdf validation service
  # has not authentication and should meanwhile only be accessible internally from 127.0.0.1
  block:
    - name: Open ports on {{ inventory_hostname }}
      ufw:
        state: enabled
        rule: allow
        proto: tcp
        from_ip: "{{ server.private_ip4_range_cidr }}"
        to_ip: any
        port : "{{ object_detection_service.port }}"

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure network on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure network FINISHED on {{ inventory_hostname }}"
  tags: ["configure_network"]
