---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Kibana service on {{ inventory_hostname }}
      template:
        src: systemd/kibana.service.j2
        dest: /etc/systemd/system/kibana.service
      register: kibana_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Kibana service on {{ inventory_hostname }}
      systemd:
        name: kibana.service
        enabled: yes
      when: kibana_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Configure startup programs FINISHED on {{ inventory_hostname }}"
  tags: ["startup_programs"]