- name: Setting up server with Kibana on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: update_app_checker.yml
      vars:
        app_dir: "{{ kibana.dir }}"
        app_version: "{{ elk_version }}"
        output_fact: kibana_will_update

    - import_tasks: u1-prepare_for_update.yml
      when: kibana_will_update
      tags: [prepare_for_update]

    - import_tasks: 02-setup_kibana.yml
      tags: [setup_kibana]

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Kibana on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Kibana FINISHED on {{ inventory_hostname }}"
  tags: ["kibana"]
