- name: Setting up server with Kibana on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: 03-setup_kibana.yml
      tags: [setup_kibana]

    - import_tasks: 04-configure_startup_programs.yml
      tags: [configure_startup_programs]

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Kibana on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Kibana FINISHED on {{ inventory_hostname }}"