---
- name: Configure startup programs on {{ inventory_hostname }}
  block:

    - name: Config Logstash service on {{ inventory_hostname }}
      template:
        src: systemd/logstash.service.j2
        dest: /etc/systemd/system/logstash.service
      register: logstash_service

    - name: Force systemd to reload configs on {{ inventory_hostname }}
      systemd:
        daemon_reload: yes

    - name: Enable Logstash service on {{ inventory_hostname }}
      systemd:
        name: logstash.service
        enabled: yes
      when: logstash_service.changed

  become: true
  become_user: root
  rescue:
    - debug:
        msg: "ERROR in Configure startup programs"
  always:
    - debug:
        msg: "Configure startup programs FINISHED"
  tags: ["startup_programs"]