- name: Setting up server with Logstash on {{ inventory_hostname }}
  block:
    - import_tasks: 01-prepare_required_packages.yml
      tags: [prepare_packages]

    - import_tasks: 02-configure_network.yml
      tags: [configure_network]

    - import_tasks: 03-setup_logstash.yml
      tags: [setup_logstash]

  rescue:
    - debug:
        msg: "ERROR in Setting up server with Logstash on {{ inventory_hostname }}"
  always:
    - debug:
        msg: "Setting up server with Logstash FINISHED on {{ inventory_hostname }}"
  tags: ["logstash"]